### ISSUE TITLE
Mysql error in admin OC 1.5.6.4

### ISSUE THREAD

**Issue by Prento956** [epiksel/free-extensions#2]
Upon installing this module the following error arised. however module works fine in database and on front end.
![admin](https://cloud.githubusercontent.com/assets/19893778/21521485/b972d1b0-ccd3-11e6-8a38-6de1dbdf5e70.png)

**Comment by ekavando** [comment]
Mysql is not installed on your server. mysql is no longer used. mysqli is used instead of mysql.
Remove code mysql_query( in xml

**Comment by Prento956** [comment]
I removed the code, now i have no access to the module in admin area to answer the customer ticket @eka7a @epiksel
